//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string CompanyName { get; set; }
        public int DiscountValue { get; set; }
        public string InvoicePrinter { get; set; }
        public string BarcodePrinter { get; set; }
        public string WhatsAppCode { get; set; }
        public string WhatsAppSender { get; set; }
        public string smtpAddress { get; set; }
        public string emailFrom { get; set; }
        public string password { get; set; }
        public Nullable<decimal> HourRate { get; set; }
    }
}
