//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUZUM_Payment
    {
        public int id { get; set; }
        public Nullable<int> Trainee_id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public string Attach_receipt { get; set; }
    
        public virtual NUZUM_Trainee NUZUM_Trainee { get; set; }
    }
}
