//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUZUM_Profile
    {
        public int id { get; set; }
        public int Trainee_id { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Tell { get; set; }
        public Nullable<System.DateTime> LastLogine { get; set; }
        public Nullable<int> Locality_id { get; set; }
    
        public virtual NUZUM_Trainee NUZUM_Trainee { get; set; }
    }
}
