//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUZUM_fees
    {
        public int id { get; set; }
        public Nullable<int> Intake_id { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual NUZUM_Intake NUZUM_Intake { get; set; }
    }
}
