//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUZUM_Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NUZUM_Trainee()
        {
            this.NUZUM_Payment = new HashSet<NUZUM_Payment>();
            this.NUZUM_Profile = new HashSet<NUZUM_Profile>();
        }
    
        public int id { get; set; }
        public string Frist_name { get; set; }
        public string Middle_name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Intake_id { get; set; }
        public Nullable<int> Learning_mode_id { get; set; }
        public byte[] Acceptance { get; set; }
        public byte[] Receipt { get; set; }
        public string CurrentJob { get; set; }
        public string IDNumber { get; set; }
        public string Email { get; set; }
    
        public virtual NUZUM_Intake NUZUM_Intake { get; set; }
        public virtual NUZUM_Learning_Mode NUZUM_Learning_Mode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUZUM_Payment> NUZUM_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUZUM_Profile> NUZUM_Profile { get; set; }
    }
}
