//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Expense
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BranchID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int InsertedUserId { get; set; }
        public string UserName { get; set; }
        public string BranchName { get; set; }
        public string InsertedUser { get; set; }
        public string FullName { get; set; }
        public string InsertedFullName { get; set; }
        public int ShiftID { get; set; }
    }
}
