//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Inventory
    {
        public string Number { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal DiscountPrice { get; set; }
        public int ReceiveQuantity { get; set; }
        public int CurrentQuanity { get; set; }
        public string Name { get; set; }
        public string BarcodeText { get; set; }
        public int ID { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string OriginalBarcodeText { get; set; }
        public Nullable<int> QuickCode { get; set; }
    }
}
