//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedaPOS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NetSummary
    {
        public System.DateTime Date { get; set; }
        public int BranchID { get; set; }
        public int SaleInvoiceID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<decimal> Ex_Total { get; set; }
    }
}
