//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Inventories = new HashSet<Inventory>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.Expenses = new HashSet<Expense>();
            this.Stockings = new HashSet<Stocking>();
            this.MarqueeMessages = new HashSet<MarqueeMessage>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Shifts = new HashSet<Shift>();
        }
    
        public int ID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Stocking> Stockings { get; set; }
        public virtual ICollection<MarqueeMessage> MarqueeMessages { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
