//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
            this.StockingDetails = new HashSet<StockingDetail>();
        }
    
        public int ID { get; set; }
        public int PurchaseInvoiceDetailID { get; set; }
        public int ReceiveQuantity { get; set; }
        public int CurrentQuanity { get; set; }
        public int Flag { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int BranchID { get; set; }
        public Nullable<bool> DoneInventory { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<int> SystemQTY { get; set; }
        public Nullable<int> ActualQTY { get; set; }
    
        public virtual PurchaseInvoiceDetail PurchaseInvoiceDetail { get; set; }
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<StockingDetail> StockingDetails { get; set; }
    }
}
