//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public MessageType()
        {
            this.UserMessages = new HashSet<UserMessage>();
        }
    
        public int ID { get; set; }
        public string Message { get; set; }
        public string Template { get; set; }
        public string EnumCoode { get; set; }
        public int CodeID { get; set; }
        public int ParameterCount { get; set; }
    
        public virtual ICollection<UserMessage> UserMessages { get; set; }
    }
}
