//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        public bool DirectPayment { get; set; }
        public string Type { get; set; }
        public string Desciption { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
