//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.Expenses = new HashSet<Expense>();
            this.ShiftUsers = new HashSet<ShiftUser>();
        }
    
        public int ID { get; set; }
        public int UserId { get; set; }
        public int BranchID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogoutTime { get; set; }
        public decimal CoinsAmountStart { get; set; }
        public decimal CoinsAmountClose { get; set; }
        public decimal CashAmountStart { get; set; }
        public decimal CashAmountClose { get; set; }
        public decimal ZainVoucherMachineBalanceStart { get; set; }
        public decimal ZainVoucherMachineBalanceClose { get; set; }
        public decimal ElectricityAmountStart { get; set; }
        public decimal ElectricityAmountClose { get; set; }
        public decimal SaleTotal { get; set; }
        public decimal DiscountTotal { get; set; }
        public decimal ExpensesTotal { get; set; }
        public decimal SystemCash { get; set; }
        public decimal UserCash { get; set; }
        public int Flag { get; set; }
        public int NoOfElectricityInvoice { get; set; }
        public Nullable<bool> Fax { get; set; }
        public Nullable<bool> ColorPrinter { get; set; }
        public Nullable<bool> LaserPrinter { get; set; }
        public Nullable<bool> Scanner { get; set; }
        public Nullable<bool> Photocopier { get; set; }
        public Nullable<bool> PackingMachine { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<ShiftUser> ShiftUsers { get; set; }
        public virtual User User { get; set; }
    }
}
