//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocking
    {
        public Stocking()
        {
            this.StockingDetails = new HashSet<StockingDetail>();
        }
    
        public int ID { get; set; }
        public int BranchID { get; set; }
        public int ItemCategoryId { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public int Flag { get; set; }
        public string Number { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ICollection<StockingDetail> StockingDetails { get; set; }
    }
}
