//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Expenses = new HashSet<Expense>();
            this.Expenses1 = new HashSet<Expense>();
            this.MarqueeMessages = new HashSet<MarqueeMessage>();
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.Requests = new HashSet<Request>();
            this.SaleInvoices = new HashSet<SaleInvoice>();
            this.Shifts = new HashSet<Shift>();
            this.UserLogins = new HashSet<UserLogin>();
            this.UserMessages = new HashSet<UserMessage>();
            this.UserPayments = new HashSet<UserPayment>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string PushoverID { get; set; }
        public Nullable<int> MaxExpensePerDay { get; set; }
        public Nullable<int> MaxExpensePerMonth { get; set; }
        public Nullable<decimal> HourRate { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Expense> Expenses1 { get; set; }
        public virtual ICollection<MarqueeMessage> MarqueeMessages { get; set; }
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<SaleInvoice> SaleInvoices { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<UserMessage> UserMessages { get; set; }
        public virtual ICollection<UserPayment> UserPayments { get; set; }
    }
}
