//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPayment
    {
        public int ID { get; set; }
        public int PaymentType { get; set; }
        public int InvoiceID { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Desciption { get; set; }
    
        public virtual User User { get; set; }
    }
}
