//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PurchaseDetails
    {
        public int ReceiveQuantity { get; set; }
        public int CurrentQuanity { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Name { get; set; }
        public int PurchaseInvoiceDetailID { get; set; }
        public int PurchaseInvoiceID { get; set; }
        public int Quantity { get; set; }
        public decimal PurchasePrice { get; set; }
        public int ID { get; set; }
        public int BranchID { get; set; }
    }
}
