//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReorderItem
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public int CurrentQuanity { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
        public System.DateTime Date { get; set; }
        public int BranchID { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public int CategoryID { get; set; }
    }
}
