//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Request
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public int BranchID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string BranchName { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string CustomerMobileNo { get; set; }
        public bool RequestByCustomer { get; set; }
        public int Status { get; set; }
    }
}
