//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Sale2
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public int Quanitity { get; set; }
        public decimal UnitPrice { get; set; }
        public System.DateTime Date { get; set; }
        public int SaleInvoiceID { get; set; }
        public string BranchName { get; set; }
        public int BranchID { get; set; }
        public int InventoryID { get; set; }
        public int ID { get; set; }
        public string Remarks { get; set; }
    }
}
