//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SaleReport
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int Flag { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string BranchName { get; set; }
        public int BranchID { get; set; }
        public string Remarks { get; set; }
    }
}
