//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StockingDetails
    {
        public int StockingID { get; set; }
        public int InventoryID { get; set; }
        public int ItemID { get; set; }
        public int SystemQTY { get; set; }
        public int ActualQNT { get; set; }
        public string Remarks { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    }
}
