//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TempItem
    {
        public int ItemID { get; set; }
        public string GroupName { get; set; }
        public string Name { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SalePrice { get; set; }
        public string BarcodeText { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int ID { get; set; }
        public int CurrentQuanity { get; set; }
        public Nullable<int> ItemOrderID { get; set; }
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> ReorderPoint { get; set; }
    }
}
